#!/usr/bin/env bash
# The gate for this repository: lint what it ships, hold the docs to the family's rules,
# and prove that each check can actually go red. A check that has never failed is a
# decoration.
#
# What this gate cannot cover is the skill's behavioural claims: they need a running
# Obsidian with a real vault, which no runner has. They carry their measurements instead,
# so a reader with an app open can falsify them — see references/pitfalls.md.
#
# Nothing here touches the network, so it is safe on pull requests.
# Needs: actionlint, shellcheck, shfmt — from the flake's dev shell, never from PATH's luck.
#
#   nix develop -c ./check.sh
set -euo pipefail

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "$HERE"

# One source of truth for what gets linted. A second copy of this list drifts, and a
# drifted list lies about what was checked.
scripts=(check.sh check-skill.sh check-pins.sh check-changelog.sh check-readme.sh)
skill_name=obsidian-cli

fail() {
  echo "check: $1" >&2
  exit 1
}

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

missing=()
for tool in actionlint shellcheck shfmt; do
  command -v "$tool" >/dev/null || missing+=("$tool")
done
((${#missing[@]} == 0)) ||
  fail "missing: ${missing[*]} — they are pinned in the flake, so run this as: nix develop -c ./check.sh"

echo "== the scripts parse and lint"
for s in "${scripts[@]}"; do bash -n "$s"; done
shellcheck "${scripts[@]}"
shfmt -d -i 2 -ci "${scripts[@]}"

echo "== the workflows are valid, and their tools come from the lock rather than a registry"
[[ -d .github/workflows ]] || fail ".github/workflows is missing — nothing gates this repository"
actionlint
# The pin guard, copied verbatim from the ci skill: it proves on every run that it catches
# each unpinned shape and stays quiet on the pinned spellings, then scans the workflows
./check-pins.sh

echo "== SKILL.md loads, every reference is reachable, and every link and anchor resolves"
# The one gate every skill repository shares, copied verbatim from the ci skill. It plants
# a defect per check on every run, so nothing here has to prove it separately
./check-skill.sh -n "$skill_name" .

echo "== the changelog obeys the versioning skill's rules"
./check-changelog.sh -n CHANGELOG.md

echo "== the readme obeys the create-readme skill's rules"
./check-readme.sh README.md

echo "== and the readme checker is awake — each planted defect is caught, naming it"
# check-readme.sh travels from another repository and carries no self-test, so this gate
# runs it against one deliberately broken copy per rule. Without this, a checker that
# silently stopped reading would read as a green run for as long as nobody looked.
planted() { # planted NAME EXPECTED-FRAGMENT <<< the broken readme
  local name="$1" want="$2" out
  cat >"$work/$name.md"
  out=$(./check-readme.sh "$work/$name.md" 2>&1) &&
    fail "the readme checker passed a readme that $name"
  [[ "$out" == *"$want"* ]] ||
    fail "the readme checker caught $name for the wrong reason: $out"
}

planted ends-with-a-full-stop 'full stop' <<'EOF'
# Title

A paragraph that ends with a full stop.
EOF

planted hard-wraps-a-paragraph 'one line' <<'EOF'
# Title

A paragraph that has been hard-wrapped by hand
across two physical lines
EOF

planted duplicates-a-file 'own file' <<'EOF'
# Title

## License

MIT
EOF

echo "== and stays quiet on the readme this repository actually ships"
# The other half: a checker that rejects everything would pass every test above while
# being useless. This is the same file the gate checked, asserted to be accepted
./check-readme.sh README.md ||
  fail "the readme checker rejected this repository's own readme — it would cry wolf"

echo "== the skill fits in what an agent loads"
# A SKILL.md that grows past a couple of hundred lines stops being the routing layer it is
# meant to be and becomes a reference nobody reads to the end. The references are where
# length belongs, and they are loaded on demand
lines=$(wc -l <SKILL.md)
((lines <= 150)) ||
  fail "SKILL.md is $lines lines — over 150, move the detail into references/"

echo "== the skill still points at help as the command reference, and says so"
# The central rule this skill exists to hold: the command set is generated by the running
# app and varies with its enabled plugins, so a transcribed list is a second source of
# truth that goes stale in silence. If that sentence ever leaves the documents, the rule
# has been dropped and the next contributor will paste a command table back in
grep -q 'help' SKILL.md ||
  fail "SKILL.md no longer names help as the command reference"
grep -q 'does not repeat it' references/commands.md ||
  fail "references/commands.md no longer says why it omits the command list"

echo "== every document states the version its measurements came from"
# A number with no version beside it cannot be checked by the next reader, which is the
# only thing that makes these claims falsifiable rather than folklore
version_claim='1\.13\.7'
for f in SKILL.md references/commands.md references/pitfalls.md; do
  grep -qE "$version_claim" "$f" ||
    fail "$f states behaviour without naming the version it was measured on"
done

echo "== and that check is awake — a document with no version is caught"
# The half that proves the loop above is doing something. Without it, a typo in the
# pattern would leave every future document unchecked and the run still green
printf '%s\n' '# A document with measurements and no version' 'It returned 12 backlinks' \
  >"$work/versionless.md"
grep -qE "$version_claim" "$work/versionless.md" &&
  fail "the version guard matches a document that names no version"

echo "check: green"
